spring.application.name=SB-DMS-SERVICE

#embeded tomcat port number
server.port=2222

#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/training
spring.datasource.username=root
spring.datasource.password=Akhila@180305
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#application properties
ems.save.success= SUCCESS : Department Object Saved
ems.update.success= SUCESS : Department Object Updated
ems.delete.success= SUCESS : Department Object Deleted

#application error properties
ems.invalid.employee-details= FAILED : Invalid Department Details
ems.invalid.employee-notfound= FAILED : Department Not Found

ems.db.failed= FAILED : DB Error

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
